version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: "url_app"
    depends_on:
      - db
    volumes:
      - .:/home/application/urlsh
  db:
    image: mysql
    environment:
      MYSQL_DATABASE: urlsh
      MYSQL_ROOT_PASSWORD: necronomicon
    ports:
      - "3306:3306"
