# Generated by Django 4.0.5 on 2022-06-16 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0002_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
