# Generated by Django 4.0.5 on 2022-06-28 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0004_urls_alter_users_managers_delete_url_urls_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='src.users'),
        ),
    ]
