# Generated by Django 4.0.5 on 2022-06-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0007_alter_urls_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urls',
            name='url',
            field=models.URLField(),
        ),
    ]
