# Generated by Django 4.0.5 on 2022-06-27 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_alter_url_short_url_alter_url_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('url', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelManagers(
            name='users',
            managers=[
            ],
        ),
        migrations.DeleteModel(
            name='Url',
        ),
        migrations.AddField(
            model_name='urls',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.users'),
        ),
    ]
