name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql user: "root"
          mysql database: "urlsh"
          character set server: "utf8"
          mysql password: "necronomicon"
          collation server: "utf8_general_ci"
          mysql root password: "necronomicon"

      - name: Run Migrations
        run: python manage.py migrate --database=ci

      - name: Run Tests
        run: python manage.py test --database=ci
